### ISSUE TITLE
개발하면서.. e

### ISSUE THREAD

**Issue by Devik0213** [Devik0213/memo#12]
# DataBinding
데이터바인딩을 사용하면서, 알수없는 이유들로 작업내용을 쑤욱 둘러보는경우가 많다.
잘못된 객체참조는 흔한이슈이며, xml 내의 id참조가 잘못되는 경우도 마찬가지 작업하며 발생하는 주의사항들을 적어보겠다.

### view/id  사용로 사용되는 naming 은 반드시 under_score 방식을 사용해야한다.
binding 객체에서 ㅁ

**Comment by Devik0213** [comment]
# Rx, Retrofit2.0, ViewModel
위 세트를 사용하다보니, ViewModel이 disposable 을 구현해주지않으면 다음과같이 딜리버리에러가 발생하는것 같다
```
  io.reactivex.exceptions.UndeliverableException: java.net.SocketException: Software caused connection abort
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableZip$ZipCoordinator.error(FlowableZip.java:153)
        at io.reactivex.internal.operators.flowable.FlowableZip$ZipSubscriber.onError(FlowableZip.java:388)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.
```
확인해보고,관련자료
https://medium.com/@bherbst/the-rxjava2-default-error-handler-e50e0cab6f9f
https://github.com/ReactiveX/RxJava/issues/4863
